.TH tlslookup 1
.SH NAME
.B tlslookup
\- resolve the internet address with DNS queries over HTTPS/TLS
.SH SYNOPSIS
.B tlslookup
\fIhost\fR
.SH DESCRIPTION
Similar to nslookup(1), tlslookup is a program to query internet domain name servers. tlslookup resolves the internet address of \fIhost\fR with DNS queries over HTTPS/TLS by talking to the nss-tlsd(8) daemon.
.SH "SEE ALSO"
.B nss-tlsd(8), nslookup(1)
.SH AUTHOR
Dima Krasner (dima@dimakrasner.com)